### PR TITLE
Offer Tool Improvements

### PR DESCRIPTION
**Pull request by RlonRyan**
While attempting to use your handy tool, I came across a few features that I needed, such as model translation, so I added them here. I thought that you, and others might like the additions I made, and find them equally as useful.

### CODE REVIEW

**Comment by phase** [comment]
Is there a reason it is named `AgiCraft` in the README?

**Comment by iLexiconn** [comment]
Please fix what @phase said, replace the tabs with spaces and remove the author tags. :)

**Comment by RlonRyan** [comment]
Oops. Sorry...

**Comment by iLexiconn** [comment]
Are you going to fix it? I'll merge it if you do.

**Comment by RlonRyan** [comment]
Yes, when I get some time this weekend.

**Comment by iLexiconn** [comment]
:+1:

**Comment by RlonRyan** [comment]
Oops I forgot about this... What else was there to do again?
I did correct the spaces, no?

**Comment by iLexiconn** [comment]
Remove the readme please.. or write a proper one. ;)

**Comment by RlonRyan** [comment]
Ah the readme! On it!

**Comment by RlonRyan** [comment]
What would you like it to say (I fixed the bad mod name)?
In the description?

**Comment by iLexiconn** [comment]
A small description, contribute guide and download link would be nice.

**Comment by RlonRyan** [comment]
How does that look?

**Comment by iLexiconn** [comment]
Thank you very much! :)

**Comment by RlonRyan** [comment]
Glad to help!

**Pull request merged**
